name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - dev # Trigger this workflow when code is pushed to the 'dev' branch
  pull_request:
    branches:
      - dev # Also run on pull requests targeting 'dev'

env:
  # General variables for your app and image naming
  IMAGE_NAME: real-estate-connect-app
  # Your Firebase config and Gemini API key for the build environment
  # IMPORTANT: Store these as GitHub Secrets.
  FIREBASE_CONFIG_VAR: ${{ secrets.FIREBASE_CONFIG }}
  APP_ID_VAR: ${{ secrets.APP_ID }} # Corrected from FIREBASE_APP_ID as per typical naming convention
  AUTH_TOKEN_VAR: ${{ secrets.AUTH_TOKEN }} # Corrected from FIREBASE_AUTH_TOKEN
  GEMINI_API_KEY_VAR: ${{ secrets.GEMINI_API_KEY }}

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    permissions:
      contents: read
      # No 'packages: write' needed as we are pushing to Docker Hub, not GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Match your Node.js version used in Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 # Required for building multi-architecture images

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Better builder for Docker

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io # Specify Docker Hub registry
          username: ${{ secrets.DOCKER_USERNAME }} # Use your Docker Hub username secret
          password: ${{ secrets.DOCKER_PASSWORD }} # Use your Docker Hub password/PAT secret

      - name: Get current date for image tag
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Tags to push to Docker Hub (your-dockerhub-username/your-image-name)
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.date.outputs.date }}
          # Pass environment variables to the Docker build process
          build-args: |
            REACT_APP_FIREBASE_CONFIG=${{ env.FIREBASE_CONFIG_VAR }}
            REACT_APP_APP_ID=${{ env.APP_ID_VAR }}
            REACT_APP_INITIAL_AUTH_TOKEN=${{ env.AUTH_TOKEN_VAR }}
            REACT_APP_GEMINI_API_KEY=${{ env.GEMINI_API_KEY_VAR }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
