# docker-compose.yml
version: '3.8'

services:
  nginx_web:
    image: ${DOCKER_USERNAME}/real-estate-connect-app:${WEB_IMAGE_TAG}
    ports:
      - "3002:80" # Expose port 3002 on host to port 80 in container
    depends_on:
      - laravel_app
    networks:
      - app-network

  laravel_app:
    image: ${DOCKER_USERNAME}/real-estate-connect-laravel:${LARAVEL_IMAGE_TAG}
    environment:
      # These must match your Laravel .env database configuration
      DB_CONNECTION: mysql
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      mysql_db:
        condition: service_healthy # Wait until MySQL is healthy before starting Laravel
    networks:
      - app-network

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Essential for root access/setup
    ports:
      - "33060:3306" # Optional: Expose MySQL for local connection/tools
    volumes:
      - db_data:/var/lib/mysql # Persist database data
    healthcheck:
      # Healthcheck to ensure database is ready
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}" ]
      timeout: 5s
      retries: 10
      interval: 3s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: # Define the named volume for database persistence
